# Generated by Django 2.2.7 on 2019-11-25 13:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('challans', '0001_initial'),
        ('parties', '0001_initial'),
        ('payment_parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(blank=True, choices=[('DP', 'Direct Payment'), ('AL', 'Account Less')], max_length=2, null=True)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2)),
                ('payed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('payed_on', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('extra_info', models.TextField(blank=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('challan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challans.Challan')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('deducted_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('previous_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='InPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('AD', 'Adjusted'), ('WL', 'Wallet'), ('CS', 'Cash')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='DN', max_length=2)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
                ('wallet_advance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.WalletAdvance')),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('payed_on', models.DateTimeField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='payments/account_transactions/photos/')),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='DN', max_length=2)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(blank=True, max_length=32, null=True)),
                ('actr_no', models.CharField(default='WGP', max_length=7, verbose_name='Payment No')),
                ('serial_no', models.CharField(blank=tuple, max_length=7, null=True, verbose_name='PY Serial No')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('payed_on', models.DateField(default=django.utils.timezone.now)),
                ('extra_info', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='payments/account_transactions/photos/')),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.BankAccount')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
                ('payment_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_parties.PaymentParty')),
            ],
        ),
    ]
