# Generated by Django 2.2.7 on 2019-11-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransaction',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payed_on',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='created_on',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='payed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='payed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inpayment',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
