# Generated by Django 2.0 on 2019-11-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191127_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='actr_no',
            field=models.CharField(default='DPP', max_length=7, verbose_name='Payment No'),
        ),
    ]
