# Generated by Django 2.0 on 2019-11-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20191128_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inpayment',
            old_name='created_on',
            new_name='payed_on',
        ),
    ]
