# Generated by Django 2.2.7 on 2019-11-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportweight',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='challan',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reportweight',
            name='reported_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
