# Generated by Django 2.0 on 2019-11-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challans', '0002_auto_20191127_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='created_on',
            field=models.DateField(verbose_name='Challan Date'),
        ),
    ]
