# Generated by Django 2.2.7 on 2019-12-02 12:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('GR', 'Group Rate'), ('IR', 'Individual Rate')], max_length=2)),
                ('name', models.CharField(max_length=128)),
                ('party_code', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=13)),
                ('whatsapp', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('extra_info', models.TextField(blank=True)),
                ('is_wallet_party', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rates.RateGroup')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('upper_limit', models.DecimalField(decimal_places=2, default=20000.0, max_digits=9)),
                ('deduct_type', models.CharField(choices=[('FD', 'Full Deduct'), ('PD', 'Part Deduct'), ('FXD', 'Fix Deduct')], max_length=3)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Party')),
            ],
        ),
        migrations.CreateModel(
            name='WalletAdvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gateway', models.CharField(choices=[('CS', 'Cash'), ('AC', 'Account'), ('IP', 'In Payment')], default='CS', max_length=2)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('payed_on', models.DateField(verbose_name='Payed On')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parties/wallets/advances/')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Wallet', verbose_name='Party')),
            ],
        ),
    ]
