# Generated by Django 2.2.7 on 2019-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dealer_code', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(max_length=13)),
                ('whatsapp', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('extra_info', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
