# Generated by Django 2.2.7 on 2019-11-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='vehicle_details',
            field=models.CharField(max_length=264),
        ),
    ]
