# Generated by Django 2.2.7 on 2019-11-30 13:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_limit', models.DecimalField(decimal_places=2, default=Decimal('1000000'), editable=False, max_digits=9)),
                ('account_holder', models.CharField(max_length=128)),
                ('acc_no', models.CharField(max_length=32)),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(limit_value=11)])),
                ('bank_name', models.CharField(max_length=64)),
                ('branch_name', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.Party')),
            ],
        ),
    ]
